### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by r9r-dev** [axel3rd/mpg-coach-bot#238] opened 2022-08-05 20:27 UTC
Hello,
There is an exception at startup.

I think the bug has been fixed since but I don't know how to launch the bot from source.

Thanks !

`Exception in thread "main" java.lang.UnsupportedOperationException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Ligue-1-2020-2021" (class org.blondin.mpg.stats.model.LeaguesRefresh), not marked as ignorable (5 known properties: "1", "2", "3", "4", "5"])
 at [Source: (File); line: 1, column: 178] (through reference chain: org.blondin.mpg.stats.model.LeaguesRefresh["Ligue-1-2020-2021"])
        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:168)
        at org.blondin.mpg.AbstractClient.get(AbstractClient.java:100)
        at org.blondin.mpg.AbstractClient.get(AbstractClient.java:92)
        at org.blondin.mpg.stats.MpgStatsClient.getLeaguesRefresh(MpgStatsClient.java:49)
        at org.blondin.mpg.stats.MpgStatsClient.getStats(MpgStatsClient.java:38)
        at org.blondin.mpg.Main.getCurrentDay(Main.java:488)
        at org.blondin.mpg.Main.calculateEfficiencies(Main.java:468)
        at org.blondin.mpg.Main.completeAuctionAndcalculateEfficiency(Main.java:443)
        at org.blondin.mpg.Main.processGames(Main.java:186)
        at org.blondin.mpg.Main.processLeague(Main.java:118)
        at org.blondin.mpg.Main.process(Main.java:82)
        at org.blondin.mpg.Main.main(Main.java:71)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Ligue-1-2020-2021" (class org.blondin.mpg.stats.model.LeaguesRefresh), not marked as ignorable (5 known properties: "1", "2", "3", "4", "5"])
 at [Source: (File); line: 1, column: 178] (through reference chain: org.blondin.mpg.stats.model.LeaguesRefresh["Ligue-1-2020-2021"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1989)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3495)
        at org.blondin.mpg.AbstractClient.readEntityFromFile(AbstractClient.java:220)
        at org.blondin.mpg.AbstractClient.call(AbstractClient.java:164)
        ... 11 more`

**Comment by axel3rd** [comment] 2022-08-05 21:59
Hi @r9r-dev, 

Thanks for the feedback. It is a duplicate of https://github.com/axel3rd/mpg-coach-bot/issues/235. If was fixed in v1.10-SNAPSHOT (development version), downloadable from [packages](https://github.com/axel3rd/mpg-coach-bot/packages/1052515) section.

For simplest usage, I have just released the v1.10, downloadable from [releases](https://github.com/axel3rd/mpg-coach-bot/releases).

Best regards

**Closed by axel3rd** 2022-08-05 21:59 UTC
Labels: bug
