### ISSUE TITLE
Options on the efficiency algorithm 

### ISSUE THREAD

**Issue by mansuydejean** [axel3rd/mpg-coach-bot#42] opened 2019-01-10 13:44 UTC
Why not having options at run-time to tweak the efficiency algorithm :
 - setting a different goal multiplier
 - using only the grades from a defined number of the past games

**Comment by axel3rd** [comment] 2019-01-10 13:52
Good idea !

> setting a different goal multiplier

Perhaps the default could be reviewed with our experience now.

> using only the grades from a defined number of the past games

Currently only the average gicen by MpgStats is used ... but yes we can re-calculate the history from past math.

**Comment by mansuydejean** [comment] 2019-01-11 09:40
All right, I'm on it
Trick question : I changed the Player class to add an "efficiencyWithoutGoals" attribute.
So for now I echo the 2 "efficiency columns".
I wanted to sort by efficiencyWithoutGoals, so I changed Main 
- Player::getEfficiency
+ Player::getEfficiencyWithoutGoals
and when I compile, the tests with my real account shows it correctly, but I have side errors that I don't understand at the end of the tests : 

[ERROR] Errors:
[ERROR]   MainTest.testProcessUpdateCompleteBoostPlayerWithMock:212->subTestProcessUpdateWithMock:225 » UnsupportedOperation
[ERROR]   MainTest.testProcessUpdateCompleteNoOptionWithMock:202->subTestProcessUpdateWithMock:225 » UnsupportedOperation
[ERROR]   MainTest.testProcessUpdateNoPlayersMiroirOptionWithMock:197->subTestProcessUpdateWithMock:225 » UnsupportedOperation
[ERROR]   MainTest.testProcessUpdateNoSubstitutesRotaldoOptionWithMock:207->subTestProcessUpdateWithMock:225 » UnsupportedOperation

**Comment by axel3rd** [comment] 2019-01-11 12:23
>  Trick question : I changed the Player class to add an "efficiencyWithoutGoals" attribute.
>  I wanted to sort by efficiencyWithoutGoals, so I changed Main

I'm not for adding some other columns/metric.
IMO, to stay simple (functionally & technically for sorting), we should have only one "efficiency" metric.
Otherwise it would become "complicated" as on MPG or MpgStarts (multiple metrics, ...).

Our "efficiency metrics" could/should be configurable (goals coeff, number of match for average calculation) or reviewed ; perhaps the `average * goals_coeff` is not the best ....

WDYT, do you have a better idea about efficiency calculation (see [concept](https://github.com/axel3rd/mpg-coach-bot#concept)) ?

----

> I don't understand at the end of the tests

No easy to give the root cause ... do you have a complete stackstrace or a branch to reproduce it ?

**Comment by mansuydejean** [comment] 2019-01-11 14:09
> WDYT, do you have a better idea about efficiency calculation (see [concept](https://github.com/axel3rd/mpg-coach-bot#concept)) ?

My feeling is that defenders and midfielders ratings are biased by goals, because it is not happening often and only "lucky" one goal can boost the grade too much, so the efficiency is not as representative
I think it is more important for strikers, and it workds well for them

My idea was to display only 2 metrics so you can have see how to goal_coeff is affecting the real grade of the player

And having also the option to set the goals_coeff and number of games for average

> 
> > I don't understand at the end of the tests
> 
> No easy to give the root cause ... do you have a complete stackstrace or a branch to reproduce it ?
 
no more stacktrace thant what I sent you
but I can push the changes on my branch if you want to test it

**Comment by axel3rd** [comment] 2019-01-11 15:01
> My feeling is that defenders and midfielders ratings are biased by goals

Yes I agree with that. 

Perhaps the consensus could be to affect the _goal_coeff_ only on attackers, or having differents _goal_coeff_ depending the line player ? (I'm really not fan to have more 1 metric, I hope/prefer that metric calculation could be optimized).

----

> I can push the changes on my branch if you want to test it

Yes, I will have a look this weekend.

**Comment by axel3rd** [comment] 2019-01-19 00:36
@mansuydejean : Agree with #46 for efficiency coefficient option (and default values) ?

**Comment by axel3rd** [comment] 2019-02-23 16:11
Closing by #46, further in #44.

**Closed by axel3rd** 2019-02-23 16:11 UTC
Labels: enhancement
